app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    path('reses/',include(('applications.reses.urls' ,'reses'),namespace='reses')),
    path('caja/',include(('applications.caja.urls' ,'caja'),namespace='caja')),
    path('carne/',include(('applications.carne.urls' ,'carne'),namespace='carne')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/reses/urls.py
from django.urls import path , include, re_path
from .views import ResesListView,UpdateResesView,AñadirAnimal,ListTropas,CreateTropa,UpdateTropa,ListarAnimales,VentaResesCreate,VentaResesUpdate,VentaResesList

urlpatterns = [
    #path('registrares/' , ResCreateView.as_view() , name='registrares'),
    path('listareses/' , ResesListView.as_view() , name='listareses'),
    path('updatereses/<int:pk>' ,UpdateResesView.as_view() , name='updatereses'),

    #path('animal/<int:pk>' ,AñadirAnimal.as_view() , name='animal'),
    path('animal/<int:pk>' ,AñadirAnimal , name='animal'),
    path('animales/<int:pk>' ,ListarAnimales.as_view() , name='animales'),

    path('tropas/' ,ListTropas.as_view() , name='tropas'),
    path('añadirtropa/' ,CreateTropa.as_view() , name='añadirtropa'),
    path('editartropa/<int:pk>' ,UpdateTropa.as_view() , name='editartropa'),

    path('venderes/<int:pk>' ,VentaResesCreate.as_view() , name='venderes'),
    path('listaresesvendidas' ,VentaResesList.as_view(), name='listaresesvendidas' ),
    path('vendereseditar/<int:pk>' ,VentaResesUpdate.as_view() , name='vendereseditar'),
]

applications/reses/models.py
from django.db import models
from applications.bases.models import ClaseModelo2
from django.db.models.signals import post_save
from django.dispatch import receiver
from applications.ventas.models import Cliente
# Create your models here.
class Tropa(ClaseModelo2):
    cant_animales = models.IntegerField()


    def __str__(self):
        return 'Tropa numero'+str(self.id)

    

class Animal(ClaseModelo2):
    numero=models.IntegerField(default=0)
    ident=models.CharField(max_length=50,blank=True, null=True)
    tropa = models.ForeignKey(Tropa, on_delete=models.CASCADE)
    peso_animal=models.FloatField(default=0)

    #def save(self):
        #self.ident='animal:{}-tropa:{}'.format(self.id ,self.tropa)
     #   super(Animal , self).save()

    def __str__(self):
        #aqui deberia retornar el identificador del animal ?
        return 'Animal'+ str(self.numero) +'-'+ str(self.tropa)
    



class Res(ClaseModelo2):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    nombre=models.CharField(default='Res' ,max_length=20)
    peso_inicial = models.FloatField(max_length=7 , default=0)
    ingreso = models.DateTimeField(auto_now_add=True)
    peso_final=models.FloatField(blank=True , null=True , default=0)
    vendida=models.BooleanField(default=False)
    
   

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Res'
        verbose_name_plural = 'Reses'

    def __str__(self):
        return self.nombre 

TB='transferencia bancaria'
MP='mercado pago'
EF='efectivo'
TJ='tarjeta'
MEDIO_PAGO=[
    (TB ,'TRANSFERENCIA BANCARIA'),
    (MP ,'MERCADO PAGO'),
    (EF ,'EFECTIVO'),
    (TJ ,'TARJETA')
]
class VentaReses(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    res=models.ForeignKey(Res, on_delete=models.CASCADE)
    precio=models.FloatField(default=0)
    medio_pago = models.CharField(max_length=15, choices=MEDIO_PAGO,default=EF )

    def __str__(self):
        return str(self.id)+'-'+str(self.precio)
    
   

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'VentaRes'
        verbose_name_plural = 'VentaReses'


@receiver(post_save, sender=Animal)
def CrearResesDeUnAnimal(sender, instance,**kwargs):
    tropa=instance.tropa            #ESTO DEBERIA ESTAR EN OTRO PROCESO
    id_animal=instance.id
   
    animal=Animal.objects.filter(id=id_animal).update(
        ident='animal{}-{}'.format(id_animal,tropa),
    )
   
    #print('desde el signal',animal) la variable animal devuelve 1 , esto quiere decir que el update fue exitoso
   
    #PROCESO PARA CREAR LAS DOS MEDIA RESES PERTENECIENTES  AL ANIMAL EN CUESTION
    reses=[]
    anm=Animal.objects.get(id=id_animal)
    for num in range(2):
        res =Res(
            animal=anm,             #aqui se deberia pasar el numero y no el id del animal
            nombre='res{}-animal{}'.format(num,anm.numero),
        )
        reses.append(res)
    Res.objects.bulk_create(reses)

#este metodo luego de realizar una venta de reses , cambia el estado de la res vendida a True
@receiver(post_save, sender=VentaReses)
def vender_reses(sender , instance,**kwargs):
    #obtener id de la res vendida
    id_res=instance.res.id
    #obtener la instancia de la res
    res=Res.objects.get(pk=id_res)
    #cambiar estado de la res
    res.vendida=True
    res.save()
    #aumentar monto de la venta al saldo del cliente
    id_cliente=instance.cliente.id

    cliente=Cliente.objects.get(pk=id_cliente)

    saldo_cliente=cliente.saldo
    print('desde el signal')
    precio_venta=instance.precio

    cliente.saldo=saldo_cliente+precio_venta

    #si se da de baja la venta con el estado=True
    if instance.estado is True:
        cliente.saldo=saldo_cliente-precio_venta

    cliente.save()

applications/vino/models.py
from django.db import models
from applications.bases.models import ClaseModelo2 , ClaseModelo


class Unidad(ClaseModelo2):
    medida=models.CharField(max_length=10)
    def __str__(self):
         return self.medida
class Bodega(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    numero=models.CharField(max_length=30, blank=True ,null=True)
    email=models.CharField(max_length=30 ,blank=True ,null=True)
    def __str__(self):
        return self.nombre
class Reserva(ClaseModelo2):
    tipo=models.CharField(max_length=20)
    descripcion=models.CharField(max_length=50, blank=True ,null=True)
    def __str__(self):
        return self.tipo

class Cepa(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
# Create your models here.
class Vino(ClaseModelo2):
    nombre=models.CharField(max_length=40)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    codigo=models.CharField(max_length=30 ,unique=True)
    precioventa=models.FloatField()
    reserva=models.ForeignKey(Reserva , on_delete=models.CASCADE)
    bodega=models.ForeignKey(Bodega ,blank=True,null=True, on_delete=models.CASCADE)
    cepa=models.ForeignKey(Cepa,blank=True,null=True,  on_delete=models.CASCADE)
    unidad=models.ForeignKey(Unidad, on_delete=models.CASCADE)
    existencia=models.IntegerField(default=0)
    ultimacompra=models.DateField(blank=True , null=True)
    sm=models.IntegerField(blank=True , null=True)
    
    class Meta:
        verbose_name='Productos'
        

    def __str__(self):
            return '{}'.format(self.nombre)


  

applications/reses/forms.py
from django import forms

from .models import Animal,Res,VentaReses



class AnimalForm(forms.ModelForm):
    class Meta:
        model=Animal
        fields=(
            'tropa',
            'peso_animal'
        )
class EditarRes(forms.ModelForm):
    class Meta:
        model=Res
        fields=('__all__')
        
        #METODO 1
        widgets = {
                'nombre': forms.TextInput(attrs={'disabled':'disabled'}),
               # 'nombre': forms.TextInput(attrs={'readonly':'True'}),
                
            }   
    #METODO 2
    def __init__(self, *args, **kwargs):
        super(EditarRes, self).__init__(*args, **kwargs)
        self.fields['animal'].widget.attrs['disabled']='disabled'
        #self.fields['nombre'].widget.attrs['disabled']='disabled'

class VenderRes(forms.ModelForm):
    class Meta:
        model=VentaReses
        fields=('res' ,'cliente' ,'precio' ,'medio_pago','estado')

applications/reses/views.py
from django.shortcuts import render ,redirect
from django.urls import reverse_lazy

# Create your views here.
from .models import Res,Animal,Tropa,VentaReses
from applications.ventas.models import Cliente
from django.views.generic import CreateView , UpdateView,ListView,FormView

from .forms import AnimalForm,EditarRes,VenderRes

'''
class ResCreateView(CreateView):
    model = Res
    fields=('peso_inicial','peso_final','nombre')
    template_name = "reses/creares.html"
    success_url=reverse_lazy('reses:listareses')
'''
    
class ResesListView(ListView):
    model=Res
    context_object_name='obj'
    template_name = "reses/listareses.html"

class UpdateResesView(UpdateView):
    model=Res
    form_class=EditarRes
    template_name = "reses/creares.html"
    success_url=reverse_lazy('reses:listareses')

class CreateTropa(CreateView):
    model=Tropa
    fields='__all__'
    template_name='reses/añadirtropa.html'
    object_name='obj'
    success_url=reverse_lazy('reses:tropas')
class UpdateTropa(UpdateView):
    model=Tropa
    fields='__all__'
    template_name='reses/añadirtropa.html'
    object_name='obj'
    success_url=reverse_lazy('reses:tropas')

class ListTropas(ListView):
    model=Tropa
    context_object_name='obj'
    template_name='reses/tropas.html'


def AñadirAnimal(request,**kwargs):
    template_name='reses/animal.html'
    contexto={}
    
    animal={}
    #OBTENGO EL ID PASADO EN LA URL PARA PODER FILTRAR LA TOPA CORRESPONDIENTE
    ID= kwargs['pk']
    tropa=Tropa.objects.filter(id=ID)
    

    if request.method=='POST':
            #OBTENGO EL ID DEL FORMULARIO
            id_tropa=request.POST.get('tropa')
            #CON ESE ID OBTENGO EL OBJETO,PORQUE SE DEBE GUARDAR UNA INSTANCIA DEL OBJETO , NO SU ID
            tropa=Tropa.objects.get(pk=id_tropa) #USO GET PORQUE OBTENGO DIRECTAMENTE EL OBJETO , SI USO FILTER OBTENGO UN QUERYSET
            peso_animal=request.POST.get('peso_animal')
           
            #obtener el numnero del animal anterior
            anm_ant=Animal.objects.filter(tropa=id_tropa).last()
            print(anm_ant)
            if anm_ant is None:
                num=0
            else:
                num=anm_ant.numero
                

            animal=Animal(
                numero=num+1,
                tropa=tropa,
                peso_animal=peso_animal,

            )  
            animal.save()
            #animal.ident='animal:{}-{}'.format(animal.id , animal.tropa)
            #animal.save()
            #HASTA AQUI ESTA CUBIERTA LA CREACION DEL ANIMAL

            
            return redirect('reses:animales',pk=ID) #se pasa el id  para filtrar el listado de animales segun la tropa


           

    contexto={
        'tropa':tropa,
    }

    return render(request, template_name,contexto)
 
class ListarAnimales(ListView):
    model=Animal 
    template_name='reses/listanimales.html'
    
    
    def get_context_data(self, **kwargs):
        context=super(ListarAnimales , self).get_context_data(**kwargs)
        id=self.kwargs['pk']

        context['lista']=Animal.objects.filter(
            tropa=id
        )
        return context
    
class VentaResesCreate(CreateView):
    form_class=VenderRes
    template_name='reses/venderes.html'
    success_url=reverse_lazy('reses:listaresesvendidas')

    
    def get_context_data(self, **kwargs):
        #SE PASA EL ID DE LA RES QUE SE QUIERE VENDER
        ID=self.kwargs['pk']

        context = super(VentaResesCreate, self).get_context_data(**kwargs)
        context['reses']=Res.objects.filter(id=ID)
        context['clientes']=Cliente.objects.filter(estado=True)
        return context


class VentaResesUpdate(UpdateView):
    model=VentaReses
    form_class=VenderRes
    context_object_name='obj'
    template_name='reses/venderes.html'
    success_url=reverse_lazy('reses:listaresesvendidas')

                 

class VentaResesList(ListView):
    model=VentaReses
    
    template_name='reses/listaventareses.html'
    context_object_name='obj'
    

'''
#class VentaResesEdit()
 def get_queryset(self):
        obj = super(VentaResesList, self).get_queryset()
        
        return obj.filter(vendida=True)
class AñadirAnimal(CreateView):
    model=Animal
    template_name='reses/animal.html'
    fields=('tropa','peso_animal')
    #form_class=AnimalForm
    #context_object_name='obj'
    success_url=reverse_lazy('reses:listareses')

    #esto funciona , pero no guardaba el ID hasta hacerse efectivo el ID en la base de datos. ya se el id definido en los modelos
    #o el que proporciona la ORM.
    #Si funcionaba con los otros campos
    #no se asigna id a un registro hasta que este se guarda con exito en la base de datos


    def form_valid(self,form):
        animal=form.save(commit=False)
        animal.ident='animal:{}-tropa{}'.format(animal.ID, animal.tropa)
        animal.save()

        return super(AñadirAnimal ,self).form_valid(form)

soluciones para crear las reses automaticamente luego de crear el animal:
1-
 
def CrearRes():
    animal=Animal.objects.last()
    res=Res(
        animal=animal,
        peso_inicial=0,
        peso_final=0,
        uc=animal.uc,
        
    )
    res.save()

llamando a la funcion al final de  la vista de añadir animal 
resultado: funcionaba pero la funcion se ejecutaba antes de crear el animal nuevo 
, por lo tanto agarraba el anterior y no el actual

class AñadirAnimal(FormView):
    #en el form view no hace falta asignar un modelo , este ya se asigna en el form relacionado a la vista
    template_name='reses/animal.html'
    form_class=AnimalForm
    context_object_name='obj'
    success_url=reverse_lazy('reses:tropas')
    

    def get_context_data(self, **kwargs):
        #este id lo obtengo de la URL
        ID= self.kwargs['pk']
        print('id',ID)

        context=super(AñadirAnimal , self).get_context_data(**kwargs)
        #HAGO FILTRO POR ID PARA ENVIAR SOLO LA TROPA CORRESPONDIENTE
        context['tropa']=Tropa.objects.filter(id=ID)
        print('----',context['tropa'])
        return context
    

    def form_valid(self,form):
        #de esta forma no se interactua directamente con la ORM de django
        
        animal=Animal(
            tropa=form.cleaned_data['tropa'],
            peso_animal=form.cleaned_data['peso_animal'],
        ) 
        animal.save()
        animal.ident='animal:{}-{}'.format(animal.id , animal.tropa)
        animal.save()
        return super(AñadirAnimal , self).form_valid(form)
'''

templates/reses/animal.html
{% extends 'base.html' %}


{% block page_content %}
<div class="col col-6"> 
<form action="" method="post">{% csrf_token %}
  <div class="col-md-8">
    <select name="tropa" id="id_tropa" class="form-control from-control-sm">
      
      {% if tropa %}
           
      {% for item in tropa  %}
      <option value="{{item.id}}">{{item}}</option>

      {% endfor %}
      <option value="0">-----------</option>
     
      {% endif %}
        
      
    </select>
</div>
<div class="col-md-8" style="margin-top: 10px;">
  <label for="peso_animal">Peso del animal</label>
  <input type="number" name="peso_animal" value="0" step="any" required="" id="id_peso_animal" class="form-control from-control-sm">

</div>
 <div class="col-md-8" style="margin-top: 10px;">
  <button class="btn btn-success" type="submit">crear</button>
  <a class="btn btn-google" href="{% url 'reses:tropas' %} ">cancelar</a>
 </div>

</form>
</div>
{% endblock page_content %}
  <script>

  </script>

templates/reses/añadirtropa.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Cepa
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-9" >
                            
                            <div style="margin: 5px;" class="input-group">
                               <label for="cant_animales" name="cant_animales">Cantidad de animales</label>
                             
                            </div>
                            {{form.cant_animales}}

                        </div>

                  <div class="col-3">
                      <label for="id_estado" name="estado">Estado</label>
                    {{form.estado}}
    
                </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'reses:tropas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}
    
  {% block js_page %}
      
  {% endblock js_page %}
 

templates/reses/listareses.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">REGISTRO DE RESES</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="">Nueva</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay registro de reses
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="btn btn-success"  href="{% url 'reses:listaresesvendidas' %}" ><i class="fas fa-list" style="margin-right: 3px;"></i>Venta de reses</a></div>
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                        <th data-sortable="true" data-field="nombre">Nombre</th>
                        <th data-sortable="true" >Animal</th>
                        <th data-sortable="true" >Tropa</th>
                      <th>Peso inicial</th>
                      <th>Peso final</th>
                      <th>Estado</th>
     <th  data-field="estado">Vender</th>
     <th  class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item}}</td>
        <td>{{item.animal.numero}}</td>
        <td>{{item.animal.tropa}}</td>
        <td>{{item.peso_inicial}}</td>
        <td>{{item.peso_final}}</td>
     
   
   
        <td>
          
          {% if  item.vendida %}
          Vendida
            {% else  %}
           No vendida
          {% endif %}
            
         
        </td>
        <td>
          {% if  item.vendida %}
        
          {% else  %}
          <a href="{% url 'reses:venderes' item.id %}" class="btn btn-google btn-circle " role="button" ><i class="fas fa-credit-card"></i></a>
           
        {% endif %}
        </td>

        <td>
            <a href="{% url 'reses:updatereses' item.id %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    
    <!--

           <td>{{item.ingreso}} | {{item.uc}}</td>
        <td> {{item.fm}} |
          {{item.um}}
        </td>
    -->

templates/reses/tropas.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Tropas registradas</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="{% url 'reses:añadirtropa' %}">Nueva tropa</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay tropas
                 {% endif %}
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                    
     <th data-field="numero" >Numero de tropa</i></th>
     <th >Cantidad de animales</th>
     <th  >Usuario creador</th>
     <th>Ultma modificacion</th>
    <th  class="all">Editar</th>
    <th>Añadir animal</th>
    <th>Lista animales</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.cant_animales}}</td>
        <td>{{item.uc}}</td>
        <td> {{item.fm}}
          {{item.um}}
        </td>
        
        <td>
            <a href="{% url 'reses:editartropa' item.pk %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
        <td><a href="{% url 'reses:animal' item.pk %}" class="btn btn-success btn-circle " role="button" ><i class="fas fa-plus"></i></a></td>
       
        <td><a href="{% url 'reses:animales' item.pk %}" class="btn btn-info btn-circle " role="button" ><i class="fas fa-list"></i></a></td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    
    

templates/reses/venderes.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Venta de res
                    </div>
                    <div class="dropdown-divider"></div>
                  
<div class="row justify-content-between">
    
    <div class="col-4" style="margin-top: 10px;">
        <label for="id_medio_pago "  style="margin-top: 10px;">Medio de pago</label>
        
        {% if obj %}
        <select name="medio_pago" id="id_medio_pago"  style="margin-top: 10px;" class="form-control">
    <option value="{{obj.medio_pago}}">{{obj.medio_pago}}</option>
        </select>
            {% else %}
            {{form.medio_pago}}
        {% endif %}
            
      
      
    </div>

    <div class="col-4"  >
        <label for="id_res" style="margin-bottom: 20px;">Media res</label>
        
        <select name="res" id="id_res" required  style="margin-bottom: 20px;" class="form-control">
            
            {% if obj %}
            <option value="{{obj.res.id}}" >{{obj.res}}</option>
                {% else %}  
                     
            {% for item in reses %}
            <option value="{{item.id}}" >{{item}}</option>
            {% endfor %}  
            
            {% endif %}
        </select>
    </div>



    
   </div>
   <div class="dropdown-divider"></div>
<div class="row justify-content-between" >
 
      
   <div class="col-6">   
   
    <label for="id_precio" style="margin-top: 20px;">Precio</label>
    <input type="text" id="id_precio" required name="precio"  class="form-control" value="{% if obj %}{{obj.precio}}{% endif %}">
 
</div>
    <div  class="col-6">
        <label for="id_cliente">Cliente</label>
     <select id="id_cliente" name="cliente" required class="form-control">
         
         {% if obj %}
         <option value="{{obj.cliente.id}}">{{obj.cliente}}</option>
         {% else %}
         {% for item in clientes %}
         <option value="{{item.id}}">{{item}}</option>
         {% endfor %}   
         {% endif %}
             
      
     </select>
    </div>
</div>
<div class="row">
    
{% if obj %}
    
<div>
    <label for="id_estado" >Dar de baja venta</label>
    {{form.estado}}
</div>

{% endif %}
    
</div>

                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'reses:listaresesvendidas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}