app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    path('reses/',include(('applications.reses.urls' ,'reses'),namespace='reses')),
    path('caja/',include(('applications.caja.urls' ,'caja'),namespace='caja')),
    path('carne/',include(('applications.carne.urls' ,'carne'),namespace='carne')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/carne/urls.py
from django.urls import path

from .views import CrearCorte , ListaCortes,ActualizarCorte
urlpatterns = [
    path('crearcorte' , CrearCorte.as_view() ,name='crearcorte'),
    path('listacortes' , ListaCortes.as_view() , name='listacortes'),
    path('actualizarcorte/<int:pk>' , ActualizarCorte.as_view() , name='actualizarcorte')
    
]

applications/reses/urls.py
from django.urls import path , include, re_path
from .views import ResesListView,UpdateResesView,AñadirAnimal,ListTropas,CreateTropa,UpdateTropa,ListarAnimales,VentaResesCreate,VentaResesUpdate,VentaResesList

urlpatterns = [
    #path('registrares/' , ResCreateView.as_view() , name='registrares'),
    path('listareses/' , ResesListView.as_view() , name='listareses'),
    path('updatereses/<int:pk>' ,UpdateResesView.as_view() , name='updatereses'),

    #path('animal/<int:pk>' ,AñadirAnimal.as_view() , name='animal'),
    path('animal/<int:pk>' ,AñadirAnimal , name='animal'),
    path('animales/<int:pk>' ,ListarAnimales.as_view() , name='animales'),

    path('tropas/' ,ListTropas.as_view() , name='tropas'),
    path('añadirtropa/' ,CreateTropa.as_view() , name='añadirtropa'),
    path('editartropa/<int:pk>' ,UpdateTropa.as_view() , name='editartropa'),

    path('venderes/<int:pk>' ,VentaResesCreate.as_view() , name='venderes'),
    path('listaresesvendidas' ,VentaResesList.as_view(), name='listaresesvendidas' ),
    path('vendereseditar/<int:pk>' ,VentaResesUpdate.as_view() , name='vendereseditar'),
]

applications/vino/urls.py
from django.urls import path , include 
from .views import CepaView ,CepaUpdate, UnidadView,UnidadNew,UnidadUpdate , BodegaView , ReservaView , VinoView,VinoNew,VinoUpdate ,CepaNew,BodegaNew,ReservaNew,BodegaUpdate,ReservaUpdate
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('cepas/',CepaView.as_view(),name='cepas'),
     path('cepas/new/',CepaNew.as_view(),name='cepanew'),
     path('cepas/cepaupdate/<int:pk>',CepaUpdate.as_view(),name='cepaupdate'),
    path('unidades/',UnidadView.as_view(),name='unidades'),
    path('unidades/unidadnew',UnidadNew.as_view(),name='crearunidad'),
    path('unidades/unidadupdate/<int:pk>/',UnidadUpdate.as_view(),name='unidadupdate'),
    path('reservas/',ReservaView.as_view(),name='reservas'),
    path('reservas/creareserva/',ReservaNew.as_view(),name='creareserva'),
     path('reservas/update/<int:pk>/',ReservaUpdate.as_view(),name='reservaupdate'),
    path('bodegas/',BodegaView.as_view(),name='bodegas'),
    path('bodegas/new/',BodegaNew.as_view(),name='crearbodega'),
    path('bodegas/update/<int:pk>/',BodegaUpdate.as_view(),name='bodegaupdate'),
    path('vinos/',VinoView.as_view(),name='vinos'),
    path('vinos/new/',VinoNew.as_view(),name='crearvino'),
    path('vinos/update/<int:pk>/',VinoUpdate.as_view(),name='vinoupdate'),
    
]

applications/carne/models.py
from django.db import models
from applications.bases.models import ClaseModelo2
# Create your models here.
class Cortes(ClaseModelo2):
    codigo=models.IntegerField(max_length=20 ,unique=True , blank=True , null=True)
    nombre = models.CharField(max_length=50 ,unique=True)
    descripcion = models.CharField(max_length=50 , blank=True , null=True)
    cant_vendida=models.FloatField(default=0)
    precio=models.FloatField(default=0)

    class Meta:
        
        verbose_name = 'CORTE DE CARNE'
        verbose_name_plural = 'CORTES DE CARNE'

    def __str__(self):
        return self.nombre

applications/vino/models.py
from django.db import models
from applications.bases.models import ClaseModelo2 , ClaseModelo


class Unidad(ClaseModelo2):
    medida=models.CharField(max_length=10)
    def __str__(self):
         return self.medida
class Bodega(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    numero=models.CharField(max_length=30, blank=True ,null=True)
    email=models.CharField(max_length=30 ,blank=True ,null=True)
    def __str__(self):
        return self.nombre
class Reserva(ClaseModelo2):
    tipo=models.CharField(max_length=20)
    descripcion=models.CharField(max_length=50, blank=True ,null=True)
    def __str__(self):
        return self.tipo

class Cepa(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
# Create your models here.
class Vino(ClaseModelo2):
    nombre=models.CharField(max_length=40)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    codigo=models.CharField(max_length=30 ,unique=True)
    precioventa=models.FloatField()
    reserva=models.ForeignKey(Reserva , on_delete=models.CASCADE)
    bodega=models.ForeignKey(Bodega ,blank=True,null=True, on_delete=models.CASCADE)
    cepa=models.ForeignKey(Cepa,blank=True,null=True,  on_delete=models.CASCADE)
    unidad=models.ForeignKey(Unidad, on_delete=models.CASCADE)
    existencia=models.IntegerField(default=0)
    ultimacompra=models.DateField(blank=True , null=True)
    sm=models.IntegerField(blank=True , null=True)
    
    class Meta:
        verbose_name='Productos'
        

    def __str__(self):
            return '{}'.format(self.nombre)


  

applications/carne/forms.py
from django import forms
from .models import Cortes

class CrearCorteForm(forms.ModelForm):
    class Meta:
        model=Cortes
        fields=('__all__')
        #labels={'medida':'Medida'}
        widget={'descripcion':forms.TextInput, 'precio':forms.NumberInput(attrs={'required':True})}

    def __init__(self, *args, **kwargs): #SE SOBRESCRIBE EL CONSTRUCTOR DEL FORMULARIO
        super().__init__(*args, **kwargs) #SE INVOCA EL CONSTRUCTOR
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })
            self.fields['cant_vendida'].widget.attrs['readonly']=True

applications/carne/views.py
from django.shortcuts import render
from .models import Cortes
from django.views.generic import CreateView,ListView,UpdateView
from django.urls import reverse_lazy
from .forms import CrearCorteForm


class CrearCorte(CreateView):
    form_class=CrearCorteForm
    template_name = "carne/crearcorte.html"
    success_url=reverse_lazy('carne:listacortes')


class ListaCortes(ListView):
    model = Cortes
    template_name = "carne/listacortes.html"
    context_object_name='obj'

class ActualizarCorte(UpdateView):
    model=Cortes
    form_class=CrearCorteForm
    context_object_name='obj'
    template_name = "carne/crearcorte.html"
    success_url=reverse_lazy('carne:listacortes')

templates/carne/crearcorte.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nuevo {% endif %} Corte                    </div>
                    <div class="dropdown-divider"></div>
                 <div class="row">
                     {{form.as_p}}
                 </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'vino:cepas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}
    
  {% block js_page %}
      
  {% endblock js_page %}
 
  <!--


   <div class="row">
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="nombre" maxlength="100" class="form-control" required id="id_nombre" placeholder="Nombre"
                                value="{% if obj %} {{ obj.nombre}} {% endif %}">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group m-1">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked 
                                {% endif %}  >
                            </div>
                        </div> 
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                            </div>
                        </div>
                      
                    </div>


  -->

templates/carne/listacortes.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown    <a href="{% url 'reses:tropas' %}" class="btn btn-google">Volver</a>-->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">CORTES DE CARNE</h6>
                  <div class="dropdown no-arrow">
                
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                        <th data-sortable="true" >Nombre</th>
                        <th data-sortable="true" >Codigo</th>
                      <th>Descripcion</th>
     <th  >Precio(por kg)</th>
     <th>Cantidad vendida(en kg)</th>
     <th  data-field="estado">Estado</th>
     <th  class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item}}</td>
        <td>{{item.codigo}}</td>
        <td>{{item.descripcion}}</td>
        <td>{{item.precio}}</td>
        <td>{{item.cant_vendida}}</td>
       
        <td>
          
          {% if  item.estado %}
          Activo
            {% else  %}
           Eliminada
          {% endif %}
            
         
        </td>
        <td>
            <a href="{% url 'carne:actualizarcorte' item.id %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    